const mockJobs = [
  {
    company: "Rhynyx",
    position: "Senior Developer",
    jobLocation: "Serzedelo",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-04-11T16:18:35Z",
  },
  {
    company: "Pixoboo",
    position: "Accountant III",
    jobLocation: "Khoronk’",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-05-10T15:10:06Z",
  },
  {
    company: "Zava",
    position: "Office Assistant IV",
    jobLocation: "Dabola",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-01-31T15:52:42Z",
  },
  {
    company: "Twitterlist",
    position: "Administrative Assistant III",
    jobLocation: "Fálanna",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-10-07T20:00:19Z",
  },
  {
    company: "Layo",
    position: "Recruiting Manager",
    jobLocation: "Matmata",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-03-17T17:51:37Z",
  },
  {
    company: "Latz",
    position: "Chief Design Engineer",
    jobLocation: "Bandaran",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-02-05T20:27:18Z",
  },
  {
    company: "Eidel",
    position: "Automation Specialist II",
    jobLocation: "Feikeng",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-02-19T05:49:12Z",
  },
  {
    company: "Aimbu",
    position: "Physical Therapy Assistant",
    jobLocation: "Vila Nova de Gaia",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-06-01T14:31:26Z",
  },
  {
    company: "Latz",
    position: "GIS Technical Architect",
    jobLocation: "Zhangjiahe",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-10-08T06:09:57Z",
  },
  {
    company: "Eazzy",
    position: "Budget/Accounting Analyst III",
    jobLocation: "Brooklyn",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2024-12-31T16:27:11Z",
  },
  {
    company: "DabZ",
    position: "Environmental Tech",
    jobLocation: "Rozivka",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-10-23T02:02:38Z",
  },
  {
    company: "Youspan",
    position: "Clinical Specialist",
    jobLocation: "Yejia",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-01-03T22:21:15Z",
  },
  {
    company: "Twinder",
    position: "Sales Representative",
    jobLocation: "Stockholm",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-01-27T20:10:49Z",
  },
  {
    company: "Babblestorm",
    position: "Tax Accountant",
    jobLocation: "Baykonyr",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-05-11T02:23:16Z",
  },
  {
    company: "Izio",
    position: "Structural Analysis Engineer",
    jobLocation: "Perho",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-04-05T09:51:04Z",
  },
  {
    company: "Jamia",
    position: "Biostatistician IV",
    jobLocation: "San Borja",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-02-13T07:05:06Z",
  },
  {
    company: "Tagchat",
    position: "Operator",
    jobLocation: "Nato",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-01-19T05:09:25Z",
  },
  {
    company: "Wordify",
    position: "Physical Therapy Assistant",
    jobLocation: "Calhetas",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-02-19T01:12:23Z",
  },
  {
    company: "Brainsphere",
    position: "Sales Representative",
    jobLocation: "Międzybrodzie Bialskie",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-06-11T06:17:57Z",
  },
  {
    company: "Zooxo",
    position: "Graphic Designer",
    jobLocation: "Karangori",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-05-02T21:03:21Z",
  },
  {
    company: "Dabshots",
    position: "VP Sales",
    jobLocation: "Bồng Sơn",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-01-26T04:59:03Z",
  },
  {
    company: "Tavu",
    position: "Legal Assistant",
    jobLocation: "Cibunar",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-07-07T23:38:47Z",
  },
  {
    company: "Ailane",
    position: "Senior Editor",
    jobLocation: "Changzhi",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-01-26T18:33:46Z",
  },
  {
    company: "Rhynyx",
    position: "Quality Engineer",
    jobLocation: "Caçapava do Sul",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-11-13T18:43:36Z",
  },
  {
    company: "Realpoint",
    position: "Software Consultant",
    jobLocation: "Shahbā",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-04-12T21:27:14Z",
  },
  {
    company: "Browsetype",
    position: "Senior Editor",
    jobLocation: "Bontoc",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-05-22T03:48:29Z",
  },
  {
    company: "Trudeo",
    position: "Professor",
    jobLocation: "Mosteiros",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-06-07T07:56:34Z",
  },
  {
    company: "Edgewire",
    position: "Civil Engineer",
    jobLocation: "Machetá",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-06-20T20:22:49Z",
  },
  {
    company: "Voolith",
    position: "Research Nurse",
    jobLocation: "Timbuktu",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-06-27T10:22:41Z",
  },
  {
    company: "Photobug",
    position: "Recruiter",
    jobLocation: "Danao",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-02-18T17:53:33Z",
  },
  {
    company: "Aibox",
    position: "Health Coach IV",
    jobLocation: "Koíla",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-07-23T23:59:14Z",
  },
  {
    company: "Yodel",
    position: "GIS Technical Architect",
    jobLocation: "Jingzhou",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-09-20T11:06:46Z",
  },
  {
    company: "Blognation",
    position: "Recruiting Manager",
    jobLocation: "Xubao",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-08-30T06:48:49Z",
  },
  {
    company: "Gabspot",
    position: "Engineer II",
    jobLocation: "Kauman",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-07-18T16:26:42Z",
  },
  {
    company: "Gabtype",
    position: "Analyst Programmer",
    jobLocation: "Hövsan",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-05-07T03:24:37Z",
  },
  {
    company: "Vinte",
    position: "Electrical Engineer",
    jobLocation: "Hulutao",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-07-01T06:10:23Z",
  },
  {
    company: "Trudeo",
    position: "Occupational Therapist",
    jobLocation: "Phu Sang",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-03-31T20:04:04Z",
  },
  {
    company: "Yakidoo",
    position: "Safety Technician IV",
    jobLocation: "Cabeças Verdes",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-02-11T07:22:39Z",
  },
  {
    company: "Agivu",
    position: "Sales Representative",
    jobLocation: "Rokytne",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-06-22T23:54:54Z",
  },
  {
    company: "Twimm",
    position: "Marketing Manager",
    jobLocation: "Natitingou",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-02-13T14:50:20Z",
  },
  {
    company: "Cogidoo",
    position: "Junior Executive",
    jobLocation: "Sayapullo",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-04-03T21:28:07Z",
  },
  {
    company: "Gigashots",
    position: "Chief Design Engineer",
    jobLocation: "Tulsa",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-06-30T02:07:35Z",
  },
  {
    company: "Oyoyo",
    position: "Human Resources Assistant IV",
    jobLocation: "Pipa",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-06-09T20:37:15Z",
  },
  {
    company: "BlogXS",
    position: "Biostatistician I",
    jobLocation: "Nizhyn",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-08-29T13:20:46Z",
  },
  {
    company: "Tazzy",
    position: "Statistician I",
    jobLocation: "Granja",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-02-09T00:04:15Z",
  },
  {
    company: "Cogibox",
    position: "Database Administrator IV",
    jobLocation: "Jagodnjak",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-03-03T06:18:25Z",
  },
  {
    company: "Skibox",
    position: "Assistant Media Planner",
    jobLocation: "Luga",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-12-18T09:12:54Z",
  },
  {
    company: "Snaptags",
    position: "Data Coordinator",
    jobLocation: "Nieszawa",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-07-21T04:55:45Z",
  },
  {
    company: "Voonte",
    position: "Technical Writer",
    jobLocation: "Mosar",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-10-02T11:23:04Z",
  },
  {
    company: "Avaveo",
    position: "Data Coordinator",
    jobLocation: "Patrol",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-10-08T13:22:22Z",
  },
  {
    company: "Yakidoo",
    position: "Web Designer II",
    jobLocation: "Krajan Kinanti",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-01-07T05:22:28Z",
  },
  {
    company: "Voonyx",
    position: "Human Resources Assistant III",
    jobLocation: "Fujinomiya",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-01-04T14:36:02Z",
  },
  {
    company: "Quatz",
    position: "Legal Assistant",
    jobLocation: "Namysłów",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-09-01T18:34:59Z",
  },
  {
    company: "Jaxworks",
    position: "Analyst Programmer",
    jobLocation: "Nyaunglebin",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-11-18T04:15:39Z",
  },
  {
    company: "Edgetag",
    position: "VP Product Management",
    jobLocation: "Rumelange",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-05-21T07:50:57Z",
  },
  {
    company: "Miboo",
    position: "Civil Engineer",
    jobLocation: "Tubualá",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-02-18T08:41:19Z",
  },
  {
    company: "Voonix",
    position: "Electrical Engineer",
    jobLocation: "Fort McMurray",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-08-26T00:01:39Z",
  },
  {
    company: "Mydo",
    position: "Payment Adjustment Coordinator",
    jobLocation: "Sumbermanggis",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-11-13T12:59:02Z",
  },
  {
    company: "Yakidoo",
    position: "Registered Nurse",
    jobLocation: "Buyun",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-01-20T01:24:33Z",
  },
  {
    company: "Buzzdog",
    position: "Editor",
    jobLocation: "Västerås",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-06-15T13:52:24Z",
  },
  {
    company: "Lazz",
    position: "Compensation Analyst",
    jobLocation: "Bawshar",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-08-01T16:15:54Z",
  },
  {
    company: "Thoughtworks",
    position: "VP Quality Control",
    jobLocation: "Dřiteň",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-04-18T21:07:37Z",
  },
  {
    company: "Talane",
    position: "Editor",
    jobLocation: "Ballisodare",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-07-20T18:54:14Z",
  },
  {
    company: "Topiclounge",
    position: "Tax Accountant",
    jobLocation: "Amiens",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-10-12T10:27:50Z",
  },
  {
    company: "Linkbridge",
    position: "Computer Systems Analyst I",
    jobLocation: "Fangshan",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-11-30T06:04:03Z",
  },
  {
    company: "Ooba",
    position: "Marketing Manager",
    jobLocation: "Vaulx-en-Velin",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-10-04T22:38:16Z",
  },
  {
    company: "Skibox",
    position: "Nurse Practicioner",
    jobLocation: "Lapa",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-02-13T23:27:17Z",
  },
  {
    company: "Tambee",
    position: "Occupational Therapist",
    jobLocation: "Huaidian",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-09-09T20:25:37Z",
  },
  {
    company: "Skyble",
    position: "Civil Engineer",
    jobLocation: "Ḩarastā",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-03-20T22:14:32Z",
  },
  {
    company: "Vidoo",
    position: "Senior Financial Analyst",
    jobLocation: "Pamarayan",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-01-20T11:28:28Z",
  },
  {
    company: "Flashset",
    position: "Office Assistant I",
    jobLocation: "Lewobelek",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-07-26T06:55:41Z",
  },
  {
    company: "Realblab",
    position: "Budget/Accounting Analyst III",
    jobLocation: "Condado",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-10-13T22:39:04Z",
  },
  {
    company: "Avaveo",
    position: "Web Developer I",
    jobLocation: "Tapayan",
    jobStatus: "pending",
    jobType: "internship",
    createdAt: "2025-02-06T11:46:13Z",
  },
  {
    company: "Photobug",
    position: "Cost Accountant",
    jobLocation: "Dera Murād Jamāli",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-11-14T12:30:07Z",
  },
  {
    company: "Trupe",
    position: "Media Manager II",
    jobLocation: "Alis",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-10-26T08:05:35Z",
  },
  {
    company: "Thoughtblab",
    position: "Programmer Analyst IV",
    jobLocation: "Lungmar",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-05-01T12:12:16Z",
  },
  {
    company: "Wikibox",
    position: "Community Outreach Specialist",
    jobLocation: "Puerto Padre",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-07-09T07:29:09Z",
  },
  {
    company: "Dabjam",
    position: "Technical Writer",
    jobLocation: "Shensuo",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-08-15T11:41:36Z",
  },
  {
    company: "Wikivu",
    position: "Dental Hygienist",
    jobLocation: "Ciilat",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-11-01T19:56:14Z",
  },
  {
    company: "Edgeclub",
    position: "Nuclear Power Engineer",
    jobLocation: "Fantan",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-09-08T05:55:31Z",
  },
  {
    company: "Zoomzone",
    position: "Dental Hygienist",
    jobLocation: "Maniwaki",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-11-19T14:35:07Z",
  },
  {
    company: "Blognation",
    position: "GIS Technical Architect",
    jobLocation: "Pontevedra",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-04-13T12:03:36Z",
  },
  {
    company: "Linktype",
    position: "Office Assistant IV",
    jobLocation: "Slovenski Javornik",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-06-24T02:42:26Z",
  },
  {
    company: "Demizz",
    position: "Community Outreach Specialist",
    jobLocation: "Dāngām",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-05-13T06:24:25Z",
  },
  {
    company: "Centizu",
    position: "Web Developer IV",
    jobLocation: "Pakuncen",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-05-01T12:40:14Z",
  },
  {
    company: "Topdrive",
    position: "Help Desk Technician",
    jobLocation: "Kréstena",
    jobStatus: "pending",
    jobType: "part-time",
    createdAt: "2025-05-27T18:06:37Z",
  },
  {
    company: "Buzzster",
    position: "Administrative Officer",
    jobLocation: "Las Cruces",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-05-30T11:44:04Z",
  },
  {
    company: "Thoughtstorm",
    position: "Community Outreach Specialist",
    jobLocation: "Mont-de-Marsan",
    jobStatus: "interview",
    jobType: "part-time",
    createdAt: "2025-07-15T17:46:35Z",
  },
  {
    company: "Tagcat",
    position: "VP Product Management",
    jobLocation: "Zlaté Hory",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-04-03T00:37:22Z",
  },
  {
    company: "Realpoint",
    position: "Developer IV",
    jobLocation: "Pinheiro Machado",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-03-14T12:13:52Z",
  },
  {
    company: "Oozz",
    position: "Senior Developer",
    jobLocation: "Quilmaná",
    jobStatus: "declined",
    jobType: "part-time",
    createdAt: "2025-04-28T06:15:29Z",
  },
  {
    company: "Aivee",
    position: "Structural Engineer",
    jobLocation: "Rudnik",
    jobStatus: "pending",
    jobType: "full-time",
    createdAt: "2025-11-24T18:48:05Z",
  },
  {
    company: "Youtags",
    position: "Programmer II",
    jobLocation: "Izlake",
    jobStatus: "declined",
    jobType: "full-time",
    createdAt: "2025-06-11T15:52:20Z",
  },
  {
    company: "Tagopia",
    position: "Food Chemist",
    jobLocation: "Wanquan",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-09-27T06:13:23Z",
  },
  {
    company: "Photolist",
    position: "VP Marketing",
    jobLocation: "Kajatian",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-07-08T00:58:47Z",
  },
  {
    company: "Oyoyo",
    position: "Web Developer I",
    jobLocation: "Łeba",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-12-13T12:28:42Z",
  },
  {
    company: "Oba",
    position: "Research Associate",
    jobLocation: "Losino-Petrovskiy",
    jobStatus: "interview",
    jobType: "full-time",
    createdAt: "2025-02-02T18:10:48Z",
  },
  {
    company: "Rhynyx",
    position: "Recruiting Manager",
    jobLocation: "Bozhou",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-06-03T01:11:28Z",
  },
  {
    company: "Brainlounge",
    position: "VP Quality Control",
    jobLocation: "Virginia",
    jobStatus: "declined",
    jobType: "internship",
    createdAt: "2025-11-28T04:06:32Z",
  },
  {
    company: "Oba",
    position: "Office Assistant III",
    jobLocation: "Biała Piska",
    jobStatus: "interview",
    jobType: "internship",
    createdAt: "2025-09-25T16:57:51Z",
  },
];

export default mockJobs;
